### ISSUE TITLE
Equipment override isn't working

### ISSUE THREAD

**Issue by Sebteddy** [cursey/kanan-new#171] opened 2020-12-22 16:22 UTC
I've been trying to use the equipment override lately i though it was my not reloading the game but i think it's something with kanan?

**Comment by sportpp** [comment] 2020-12-27 03:52
Confirmed Equip Override doesn't work

**Comment by cursey** [comment] 2020-12-27 03:55
I'll fix it soon.

**Comment by cursey** [comment] 2020-12-27 19:58
Should be fixed by commit a3aa8af77d6d1e6ba86e22710fc30e1603db1e3d. Download the latest and let me know if it works for you.

**Comment by sportpp** [comment] 2020-12-31 01:38
Working as intended. Thanks Cursey!

**Closed** 2020-12-31 01:40 UTC
