### ISSUE TITLE
Equipment Override

### ISSUE THREAD

**Issue by realxipen** [cursey/kanan-new#141] opened 2020-02-28 18:41 UTC
Hey is there any chance we can get this updated? very useful but hasn't worked past few patches

**Comment by ericchase** [comment] 2020-03-21 05:54
The equipment override mod does work. Is there something specific that doesn't seem to work for you?

**Comment by cursey** [comment] 2020-03-21 20:38
Closing because it was confirmed working in another issue.

**Closed by cursey** 2020-03-21 20:38 UTC
